version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: curotec_fullstack_pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: curotec
      POSTGRES_PASSWORD: curotecpass
      POSTGRES_DB: curotecdb
    volumes:
      - curotecpgdata:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: curotec_server
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://curotec:curotecpass@postgres:5432/curotecdb
      CLIENT_URL: http://localhost:8000
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: http://localhost:3000
    container_name: curotec_client
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - server

volumes:
  curotecpgdata:
